[package]
name = "rvfm"
version = "0.1.0"
edition = "2021"
links = "rvfm"
build = "build.rs"

[lib]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.16"
